/* ================================================================== */
/*  INGREDIENT DETAILS — Rich data for /ingredients/[key] pages        */
/*  Extends IngredientNutrition with descriptions, tips, alternatives  */
/* ================================================================== */

import type { IngredientCategory } from "./ingredient-db";

export interface IngredientAlternative {
  key: string;
  name: string;
  nameEn: string;
  replacementRatio: number; // e.g. 1.2 means use 1.2x amount
  proteinImpact: string; // e.g. "أقل بـ ٢٠٪"
  energyImpact: string;
  costImpact: string;
}

export interface IngredientDetail {
  key: string;
  category: IngredientCategory;
  description: string;
  descriptionEn: string;
  uses: string;
  usesEn: string;
  pros: string[];
  prosEn: string[];
  cons: string[];
  consEn: string[];
  whenToUse: string;
  whenToUseEn: string;
  whenNotToUse: string;
  whenNotToUseEn: string;
  alternatives: IngredientAlternative[];
}

export const INGREDIENT_DETAILS: Record<string, IngredientDetail> = {
  corn: {
    key: "corn",
    category: "energy",
    description: "الذرة الصفراء هي المصدر الرئيسي للطاقة في علائق الماشية والدواجن في مصر. تحتوي على نسبة عالية من النشا سهل الهضم وقليلة الألياف.",
    descriptionEn: "Yellow corn is the primary energy source in livestock and poultry rations in Egypt. High in easily digestible starch and low in fiber.",
    uses: "تستخدم في جميع علائق المجترات والدواجن كمصدر طاقة رئيسي. تدخل بنسبة ٣٠-٦٥٪ من العليقة حسب نوع الحيوان.",
    usesEn: "Used in all ruminant and poultry rations as the primary energy source. Constitutes 30-65% of the ration depending on animal type.",
    pros: ["طاقة عالية سهلة الهضم", "متوفرة بكثرة في السوق المصري", "مستساغة للحيوان", "قليلة الألياف"],
    prosEn: ["High easily digestible energy", "Widely available in Egyptian market", "Palatable to animals", "Low fiber"],
    cons: ["منخفضة البروتين", "معرضة للإصابة بالفطريات إذا رطبت", "سعرها يتأرجح بشكل موسمي"],
    consEn: ["Low protein", "Susceptible to fungal contamination if moist", "Seasonal price fluctuations"],
    whenToUse: "عند الحاجة لطاقة عالية في عليقة الأبقار الحلوب عالية الإنتاج أو دجاج التسمين.",
    whenToUseEn: "When high energy is needed for high-producing dairy cows or broiler chickens.",
    whenNotToUse: "في علائق الحيوانات التي تحتاج ألياف عالية بدون الحاجة لطاقة مركزة.",
    whenNotToUseEn: "In rations for animals needing high fiber without concentrated energy.",
    alternatives: [
      { key: "barley", name: "شعير", nameEn: "Barley", replacementRatio: 1.1, proteinImpact: "أعلى بـ ٣٪", energyImpact: "أقل بـ ٤٪", costImpact: "أرخص أو مماثل" },
      { key: "sorghum", name: "سورجم", nameEn: "Sorghum", replacementRatio: 1.05, proteinImpact: "أعلى بـ ١.٥٪", energyImpact: "أقل بـ ٦٪", costImpact: "أرخص" },
    ],
  },
  barley: {
    key: "barley",
    category: "energy",
    description: "الشعير مصدر طاقة جيد يحتوي على نسبة بروتين أعلى من الذرة ويستخدم بكثرة في علائق التسمين.",
    descriptionEn: "Barley is a good energy source with higher protein than corn, widely used in fattening rations.",
    uses: "يستخدم في علائق تسمين العجول والجاموس بنسبة تصل إلى ٣٠٪.",
    usesEn: "Used in calf and buffalo fattening rations up to 30%.",
    pros: ["بروتين أعلى من الذرة", "جيد للهضم", "يحسن من صحة الكرش"],
    prosEn: ["Higher protein than corn", "Good digestibility", "Improves rumen health"],
    cons: ["طاقة أقل من الذرة", "يحتوي على بيتا جلوكان قد يقلل الهضم عند الدواجن"],
    consEn: ["Lower energy than corn", "Contains beta-glucan which may reduce digestion in poultry"],
    whenToUse: "في علائق التسمين حيث البروتين المعتدل مطلوب مع طاقة جيدة.",
    whenToUseEn: "In fattening rations where moderate protein with good energy is needed.",
    whenNotToUse: "بكميات كبيرة في علائق الدواجن بسبب البيتا جلوكان.",
    whenNotToUseEn: "In large amounts in poultry rations due to beta-glucan.",
    alternatives: [
      { key: "corn", name: "ذرة صفراء", nameEn: "Yellow Corn", replacementRatio: 0.9, proteinImpact: "أقل بـ ٣٪", energyImpact: "أعلى بـ ٤٪", costImpact: "أغلى" },
      { key: "sorghum", name: "سورجم", nameEn: "Sorghum", replacementRatio: 0.95, proteinImpact: "مماثل", energyImpact: "أقل بـ ٢٪", costImpact: "أرخص" },
    ],
  },
  sorghum: {
    key: "sorghum",
    category: "energy",
    description: "السورجم (الدخن) مصدر طاقة بديل للذرة، أكثر تحملاً للجفاف وأرخص سعراً.",
    descriptionEn: "Sorghum is an alternative energy source to corn, more drought-tolerant and cheaper.",
    uses: "بديل اقتصادي للذرة في علائق المجترات والدواجن.",
    usesEn: "Economic alternative to corn in ruminant and poultry rations.",
    pros: ["أرخص من الذرة", "يحتمل الجفاف", "بروتين معتدل"],
    prosEn: ["Cheaper than corn", "Drought-tolerant", "Moderate protein"],
    cons: ["طاقة أقل من الذرة", "يحتوي على تانين قد يقلل الهضم"],
    consEn: ["Lower energy than corn", "Contains tannins which may reduce digestion"],
    whenToUse: "عند ارتفاع سعر الذرة أو الحاجة لتقليل التكلفة.",
    whenToUseEn: "When corn prices are high or cost reduction is needed.",
    whenNotToUse: "في علائق الدواجن الصغيرة بسبب التانين.",
    whenNotToUseEn: "In young poultry rations due to tannins.",
    alternatives: [
      { key: "corn", name: "ذرة صفراء", nameEn: "Yellow Corn", replacementRatio: 0.95, proteinImpact: "أقل بـ ١.٥٪", energyImpact: "أعلى بـ ٦٪", costImpact: "أغلى" },
      { key: "barley", name: "شعير", nameEn: "Barley", replacementRatio: 1.05, proteinImpact: "أعلى بـ ١.٥٪", energyImpact: "أعلى بـ ٢٪", costImpact: "مماثل" },
    ],
  },
  bran: {
    key: "bran",
    category: "energy",
    description: "ردة القمح منتج ثانوي من مطاحن القمح، تحتوي على بروتين وألياف معتدلة وتستخدم كمصدر طاقة اقتصادي.",
    descriptionEn: "Wheat bran is a byproduct of wheat milling, containing moderate protein and fiber, used as an economic energy source.",
    uses: "تستخدم في علائق المجترات بنسبة ١٠-٢٥٪ كمصدر طاقة وبروتين اقتصادي.",
    usesEn: "Used in ruminant rations at 10-25% as an economic energy and protein source.",
    pros: ["اقتصادية", "بروتين معتدل ١٥٪", "تحسن من حركة الكرش"],
    prosEn: ["Economical", "Moderate protein 15%", "Improves rumen motility"],
    cons: ["طاقة أقل من الذرة", "عالية الفوسفور", "تتأثر بالأكسدة"],
    consEn: ["Lower energy than corn", "High phosphorus", "Susceptible to oxidation"],
    whenToUse: "في علائق التسمين والأبقار الحلوب كتخفيض للتكلفة.",
    whenToUseEn: "In fattening and dairy rations to reduce cost.",
    whenNotToUse: "بكميات كبيرة في علائق الدواجن بسبب الألياف.",
    whenNotToUseEn: "In large amounts in poultry rations due to fiber.",
    alternatives: [
      { key: "rice_bran", name: "نخالة أرز", nameEn: "Rice Bran", replacementRatio: 0.85, proteinImpact: "أقل بـ ٢.٥٪", energyImpact: "أقل بـ ٢٪", costImpact: "أرخص" },
    ],
  },
  rice_bran: {
    key: "rice_bran",
    category: "energy",
    description: "نخالة الأرز منتج ثانوي من مطاحن الأرز، تحتوي على دهون عالية وطاقة جيدة لكن بحذر بسبب الأكسدة.",
    descriptionEn: "Rice bran is a rice milling byproduct with high fat and good energy, but needs care due to oxidation.",
    uses: "تستخدم بكميات محدودة (حتى ١٥٪) في علائق المجترات.",
    usesEn: "Used in limited amounts (up to 15%) in ruminant rations.",
    pros: ["دهون عالية = طاقة عالية", "اقتصادية", "بروتين معتدل"],
    prosEn: ["High fat = high energy", "Economical", "Moderate protein"],
    cons: ["سريعة الأكسدة", "عالية الفوسفور", "قد تحتوي على سيليكا"],
    consEn: ["Quick oxidation", "High phosphorus", "May contain silica"],
    whenToUse: "في علائق التسمين لزيادة كثافة الطاقة بكلفة منخفضة.",
    whenToUseEn: "In fattening rations to increase energy density at low cost.",
    whenNotToUse: "إذا لم تكن معالزة مضادة للأكسدة أو في علائق الدواجن بكميات كبيرة.",
    whenNotToUseEn: "If not antioxidant-treated or in large amounts in poultry.",
    alternatives: [
      { key: "bran", name: "ردة قمح", nameEn: "Wheat Bran", replacementRatio: 1.15, proteinImpact: "أعلى بـ ٢.٥٪", energyImpact: "أعلى بـ ٢٪", costImpact: "أغلى قليلاً" },
    ],
  },
  molasses: {
    key: "molasses",
    category: "energy",
    description: "المولاس (العسل الأسود) منتج ثانوي من قصب السكر، مصدر طاقة سريع ويحسن من استساغة العليقة.",
    descriptionEn: "Molasses is a sugarcane byproduct, a quick energy source that improves ration palatability.",
    uses: "تستخدم بنسبة ٣-١٠٪ لتحسين الطعم وتقليل الغبار وربط العليقة.",
    usesEn: "Used at 3-10% to improve taste, reduce dust, and bind the ration.",
    pros: ["تحسن الاستساغة", "تقلل الغبار", "مصدر طاقة سريع", "تساعد في كبس العليقة"],
    prosEn: ["Improves palatability", "Reduces dust", "Quick energy source", "Helps pellet binding"],
    cons: ["عالية السكر", "قد تسبب إسهال إذا زادت", "صعبة التخزين"],
    consEn: ["High sugar", "May cause diarrhea if excessive", "Difficult storage"],
    whenToUse: "لتحسين طعم العليقة أو ربط المكوّنات في العليقة المضغوطة.",
    whenToUseEn: "To improve ration taste or bind ingredients in pelleted rations.",
    whenNotToUse: "بكميات كبيرة للحيوانات الحساسة للسكر.",
    whenNotToUseEn: "In large amounts for sugar-sensitive animals.",
    alternatives: [],
  },
  soybean44: {
    key: "soybean44",
    category: "protein",
    description: "كسب فول الصويا ٤٤٪ هو المصدر البروتيني الأكثر شيوعاً في علائق الماشية والدواجن. بروتين عالي الجودة وسهل الهضم.",
    descriptionEn: "Soybean meal 44% is the most common protein source in livestock and poultry rations. High-quality, easily digestible protein.",
    uses: "المصدر البروتيني الرئيسي في معظم العلائق بنسبة ٥-٣٥٪ حسب نوع الحيوان.",
    usesEn: "The primary protein source in most rations at 5-35% depending on animal type.",
    pros: ["بروتين عالي ٤٤٪", "أحماض أمينية متوازنة", "سهل الهضم", "متوفر بكثرة"],
    prosEn: ["High protein 44%", "Balanced amino acids", "Easily digestible", "Widely available"],
    cons: ["غالية الثمن", "قد تحتوي على مثبطات إذا غير معالجة حرارياً"],
    consEn: ["Expensive", "May contain antinutritional factors if not heat-treated"],
    whenToUse: "في كل العلائق التي تحتاج بروتين عالي الجودة.",
    whenToUseEn: "In all rations needing high-quality protein.",
    whenNotToUse: "لا توجد قيود كبيرة إذا كانت معالجة حرارياً.",
    whenNotToUseEn: "No major restrictions if properly heat-treated.",
    alternatives: [
      { key: "soybean46", name: "كسب صويا ٤٦٪", nameEn: "Soybean Meal 46%", replacementRatio: 0.95, proteinImpact: "أعلى بـ ٢٪", energyImpact: "مماثل", costImpact: "أغلى قليلاً" },
      { key: "cottonseed", name: "كسب قطن", nameEn: "Cottonseed Meal", replacementRatio: 1.8, proteinImpact: "أقل بـ ٢٠٪", energyImpact: "أقل بـ ١٢٪", costImpact: "أرخص" },
      { key: "sunflower", name: "كسب عباد الشمس", nameEn: "Sunflower Meal", replacementRatio: 1.5, proteinImpact: "أقل بـ ١٤٪", energyImpact: "أقل بـ ١٦٪", costImpact: "أرخص" },
    ],
  },
  soybean46: {
    key: "soybean46",
    category: "protein",
    description: "كسب فول الصويا ٤٦٪ نسخة أعلى بروتين من كسب الصويا، مناسبة للعلائق عالية البروتين كالكتاكيت.",
    descriptionEn: "Soybean meal 46% is a higher-protein version, suitable for high-protein rations like broiler starters.",
    uses: "في علائق الدواجن عالية البروتين خاصة كتاكيت البادي.",
    usesEn: "In high-protein poultry rations, especially broiler starters.",
    pros: ["بروتين أعلى ٤٦٪", "أحماض أمينية ممتازة", "مناسب للدواجن"],
    prosEn: ["Higher protein 46%", "Excellent amino acids", "Suitable for poultry"],
    cons: ["أغلى من ٤٤٪", "قد لا يكون متوفراً دائماً"],
    consEn: ["More expensive than 44%", "May not always be available"],
    whenToUse: "في علائق الكتاكيت والدواجن التي تحتاج بروتين عالي جداً.",
    whenToUseEn: "In chick and poultry rations needing very high protein.",
    whenNotToUse: "في العلائق التي لا تحتاج بروتين عالي (تكون مكلفة بدون داعٍ).",
    whenNotToUseEn: "In rations not needing high protein (unnecessarily expensive).",
    alternatives: [
      { key: "soybean44", name: "كسب صويا ٤٤٪", nameEn: "Soybean Meal 44%", replacementRatio: 1.05, proteinImpact: "أقل بـ ٢٪", energyImpact: "مماثل", costImpact: "أرخص قليلاً" },
    ],
  },
  cottonseed: {
    key: "cottonseed",
    category: "protein",
    description: "كسب القطن مصدر بروتين اقتصادي، لكن يجب الحذر من الجوسيبول خاصة في علائق الدواجن البياضة.",
    descriptionEn: "Cottonseed meal is an economic protein source, but gossypol must be watched, especially in layer rations.",
    uses: "في علائق المجترات بنسبة تصل إلى ٢٠٪. محدود في الدواجن.",
    usesEn: "In ruminant rations up to 20%. Limited in poultry.",
    pros: ["اقتصادي", "بروتين جيد ٢٤٪", "مناسب للمجترات"],
    prosEn: ["Economical", "Good protein 24%", "Suitable for ruminants"],
    cons: ["يحتوي على جوسيبول", "يجب تحديده للدواجن البياضة", "بروتين أقل من الصويا"],
    consEn: ["Contains gossypol", "Must be limited for layers", "Lower protein than soybean"],
    whenToUse: "في علائق المجترات لتقليل التكلفة.",
    whenToUseEn: "In ruminant rations to reduce cost.",
    whenNotToUse: "في علائق الدجاج البياض (الجوسيبول يلون صفار البيض).",
    whenNotToUseEn: "In layer rations (gossypol discolors egg yolk).",
    alternatives: [
      { key: "soybean44", name: "كسب صويا ٤٤٪", nameEn: "Soybean Meal 44%", replacementRatio: 0.55, proteinImpact: "أعلى بـ ٢٠٪", energyImpact: "أعلى بـ ١٢٪", costImpact: "أغلى" },
      { key: "sunflower", name: "كسب عباد الشمس", nameEn: "Sunflower Meal", replacementRatio: 0.8, proteinImpact: "أعلى بـ ٦٪", energyImpact: "أقل بـ ٤٪", costImpact: "مماثل" },
    ],
  },
  sunflower: {
    key: "sunflower",
    category: "protein",
    description: "كسب عباد الشمس مصدر بروتين متوسط، اقتصادي ومناسب للمجترات. يحتوي على ألياف أعلى من الصويا.",
    descriptionEn: "Sunflower meal is a medium protein source, economical and suitable for ruminants. Higher fiber than soybean.",
    uses: "في علائق المجترات بنسبة تصل إلى ١٥٪.",
    usesEn: "In ruminant rations up to 15%.",
    pros: ["اقتصادي", "بروتين معتدل ٣٠٪", "لا يحتوي على جوسيبول"],
    prosEn: ["Economical", "Moderate protein 30%", "No gossypol"],
    cons: ["ألياف عالية", "بروتين أقل من الصويا", "أحماض أمينية أقل توازناً"],
    consEn: ["High fiber", "Lower protein than soybean", "Less balanced amino acids"],
    whenToUse: "كبديل اقتصادي للصويا في علائق المجترات.",
    whenToUseEn: "As an economic alternative to soybean in ruminant rations.",
    whenNotToUse: "في علائق الدواجن بكميات كبيرة بسبب الألياف.",
    whenNotToUseEn: "In large amounts in poultry rations due to fiber.",
    alternatives: [
      { key: "cottonseed", name: "كسب قطن", nameEn: "Cottonseed Meal", replacementRatio: 1.25, proteinImpact: "أقل بـ ٦٪", energyImpact: "أعلى بـ ٤٪", costImpact: "مماثل" },
      { key: "soybean44", name: "كسب صويا ٤٤٪", nameEn: "Soybean Meal 44%", replacementRatio: 0.67, proteinImpact: "أعلى بـ ١٤٪", energyImpact: "أعلى بـ ١٦٪", costImpact: "أغلى" },
    ],
  },
  linseed: {
    key: "linseed",
    category: "protein",
    description: "كسب الكتان مصدر بروتين يحتوي على أوميجا ٣، مفيد لصحة الحيوان لكن بكميات محدودة.",
    descriptionEn: "Linseed meal is a protein source containing omega-3, beneficial for animal health but in limited amounts.",
    uses: "في علائق المجترات بنسبة تصل إلى ١٥٪.",
    usesEn: "In ruminant rations up to 15%.",
    pros: ["يحتوي على أوميجا ٣", "بروتين جيد ٣٢٪", "يحسن صحة الجلد"],
    prosEn: ["Contains omega-3", "Good protein 32%", "Improves skin health"],
    cons: ["يحتوي على سيانوجينات", "يجب تحديده", "أقل توافراً"],
    consEn: ["Contains cyanogens", "Must be limited", "Less available"],
    whenToUse: "لتحسين القيمة الصحية للعليقة في كميات صغيرة.",
    whenToUseEn: "To improve ration health value in small amounts.",
    whenNotToUse: "بكميات كبيرة بسبب السيانوجينات.",
    whenNotToUseEn: "In large amounts due to cyanogens.",
    alternatives: [
      { key: "soybean44", name: "كسب صويا ٤٤٪", nameEn: "Soybean Meal 44%", replacementRatio: 0.7, proteinImpact: "أعلى بـ ١٢٪", energyImpact: "أعلى بـ ١٢٪", costImpact: "أغلى" },
    ],
  },
  fava_bean: {
    key: "fava_bean",
    category: "protein",
    description: "الفول البلدي مصدر بروتين محلي، اقتصادي ومتوفر في مصر. يحتوي على بروتين متوسط وطاقة جيدة.",
    descriptionEn: "Fava bean is a local protein source, economical and available in Egypt. Contains moderate protein and good energy.",
    uses: "في علائق المجترات والدواجن بنسبة تصل إلى ٢٥٪.",
    usesEn: "In ruminant and poultry rations up to 25%.",
    pros: ["محلي ومتوفر", "بروتين جيد ٢٤٪", "اقتصادي"],
    prosEn: ["Local and available", "Good protein 24%", "Economical"],
    cons: ["يحتوي على تانين", "يجب معالجته حرارياً", "بروتين أقل من الصويا"],
    consEn: ["Contains tannins", "Needs heat treatment", "Lower protein than soybean"],
    whenToUse: "كبديل اقتصادي محلي للصويا.",
    whenToUseEn: "As a local economic alternative to soybean.",
    whenNotToUse: "بدون معالجة حرارية للحيوانات الصغيرة.",
    whenNotToUseEn: "Without heat treatment for young animals.",
    alternatives: [
      { key: "soybean44", name: "كسب صويا ٤٤٪", nameEn: "Soybean Meal 44%", replacementRatio: 0.55, proteinImpact: "أعلى بـ ٢٠٪", energyImpact: "أعلى بـ ٤٪", costImpact: "أغلى" },
    ],
  },
  peanut: {
    key: "peanut",
    category: "protein",
    description: "كسب الفول السوداني مصدر بروتين اقتصادي لكن يجب الحذر من الأفلاتوكسين.",
    descriptionEn: "Peanut meal is an economic protein source but aflatoxin contamination must be watched.",
    uses: "في علائق المجترات بنسبة محدودة.",
    usesEn: "In ruminant rations in limited amounts.",
    pros: ["اقتصادي", "بروتين جيد ٢٦٪", "مستساغ"],
    prosEn: ["Economical", "Good protein 26%", "Palatable"],
    cons: ["عرضة للأفلاتوكسين", "يجب فحصه قبل الاستخدام", "غير مناسب للدواجن البياضة"],
    consEn: ["Susceptible to aflatoxin", "Must be tested before use", "Not suitable for layers"],
    whenToUse: "بعد التأكد من خلوها من الأفلاتوكسين.",
    whenToUseEn: "After confirming it's free of aflatoxin.",
    whenNotToUse: "إذا كان هناك شك في التلوث بالأفلاتوكسين.",
    whenNotToUseEn: "If there's any suspicion of aflatoxin contamination.",
    alternatives: [
      { key: "soybean44", name: "كسب صويا ٤٤٪", nameEn: "Soybean Meal 44%", replacementRatio: 0.6, proteinImpact: "أعلى بـ ١٨٪", energyImpact: "أعلى بـ ٦٪", costImpact: "أغلى" },
    ],
  },
  hay: {
    key: "hay",
    category: "fiber",
    description: "البرسيم الجاف (الدريس) هو المصدر الرئيسي للعلف الخشن في مصر، غني بالبروتين والألياف ومستساغ جداً.",
    descriptionEn: "Dried clover (hay) is the primary roughage source in Egypt, rich in protein and fiber and very palatable.",
    uses: "أساسي في علائق المجترات بنسبة ١٠-٥٠٪ لتوفير الألياف والبروتين.",
    usesEn: "Essential in ruminant rations at 10-50% for fiber and protein.",
    pros: ["بروتين جيد ١٧٪", "ألياف ممتازة للكرش", "مستساغ جداً", "متوفر محلياً"],
    prosEn: ["Good protein 17%", "Excellent fiber for rumen", "Very palatable", "Locally available"],
    cons: ["تتأثر جودتها بموسم الحصاد", "قد تكون غالية في غير موسمها", "مساحة تخزين كبيرة"],
    consEn: ["Quality affected by harvest season", "May be expensive off-season", "Large storage space"],
    whenToUse: "في كل علائق المجترات كمصدر أساسي للألياف.",
    whenToUseEn: "In all ruminant rations as a primary fiber source.",
    whenNotToUse: "في علائق الدواجن (لا تحتاج علفاً خشناً).",
    whenNotToUseEn: "In poultry rations (no roughage needed).",
    alternatives: [
      { key: "corn_silage", name: "سيلاج ذرة", nameEn: "Corn Silage", replacementRatio: 2.5, proteinImpact: "أقل بـ ٩٪", energyImpact: "أعلى بـ ١٢٪", costImpact: "أرخص" },
      { key: "straw", name: "تبن قمح", nameEn: "Wheat Straw", replacementRatio: 0.5, proteinImpact: "أقل بـ ١٤٪", energyImpact: "أقل بـ ١٦٪", costImpact: "أرخص بكثير" },
    ],
  },
  corn_silage: {
    key: "corn_silage",
    category: "fiber",
    description: "سيلاج الذرة علف مخمر عالي الطاقة، اقتصادي ومناسب للمجترات خاصة في موسم وفرة الذرة.",
    descriptionEn: "Corn silage is fermented high-energy forage, economical and suitable for ruminants especially in corn season.",
    uses: "في علائق المجترات بنسبة تصل إلى ٦٠٪ خاصة للأبقار الحلوب.",
    usesEn: "In ruminant rations up to 60%, especially for dairy cows.",
    pros: ["طاقة عالية للعلف الخشن", "اقتصادي", "يحسن من إنتاج اللبن", "قابل للتخزين فترات طويلة"],
    prosEn: ["High energy for roughage", "Economical", "Improves milk production", "Long storage life"],
    cons: ["يحتاج صوامع تخزين", "جودة التخزين حرجة", "المادة الجافة منخفضة ٣٥٪"],
    consEn: ["Needs storage silos", "Storage quality is critical", "Low dry matter 35%"],
    whenToUse: "في علائق الأبقار الحلوب عالية الإنتاج.",
    whenToUseEn: "In high-producing dairy cow rations.",
    whenNotToUse: "في علائق الدواجن أو إذا لم تتوفر صوامع التخزين.",
    whenNotToUseEn: "In poultry rations or if storage silos aren't available.",
    alternatives: [
      { key: "hay", name: "برسيم جاف", nameEn: "Hay", replacementRatio: 0.4, proteinImpact: "أعلى بـ ٩٪", energyImpact: "أقل بـ ١٢٪", costImpact: "أغلى" },
    ],
  },
  straw: {
    key: "straw",
    category: "fiber",
    description: "تبن القمح علف خشن منخفض القيمة الغذائية لكنه اقتصادي ويوفر الألياف اللازمة للكرش.",
    descriptionEn: "Wheat straw is low-nutritional-value roughage but economical and provides necessary rumen fiber.",
    uses: "في علائق التسمين بنسبة محدودة لتوفير الألياف بكلفة منخفضة.",
    usesEn: "In fattening rations in limited amounts for low-cost fiber.",
    pros: ["رخيص جداً", "متوفر بكثرة", "يوفر الألياف"],
    prosEn: ["Very cheap", "Widely available", "Provides fiber"],
    cons: ["بروتين منخفض جداً ٣٪", "طاقة منخفضة", "استساغة أقل"],
    consEn: ["Very low protein 3%", "Low energy", "Lower palatability"],
    whenToUse: "لتوفير الألياف بكلفة منخفضة في علائق التسمين.",
    whenToUseEn: "To provide low-cost fiber in fattening rations.",
    whenNotToUse: "في علائق الأبقار الحلوب عالية الإنتاج (طاقة منخفضة جداً).",
    whenNotToUseEn: "In high-producing dairy rations (too low energy).",
    alternatives: [
      { key: "hay", name: "برسيم جاف", nameEn: "Hay", replacementRatio: 2, proteinImpact: "أعلى بـ ١٤٪", energyImpact: "أعلى بـ ١٦٪", costImpact: "أغلى" },
    ],
  },
  limestone: {
    key: "limestone",
    category: "mineral",
    description: "كربونات الكالسيوم ( الحجر الجيري) مصدر أساسي للكالسيوم، ضروري لقوة العظام وصفار البيض.",
    descriptionEn: "Limestone (calcium carbonate) is a primary calcium source, essential for bone strength and eggshell quality.",
    uses: "في علائق الدواجن البياضة بنسبة ٣-٨٪، والمجترات ٠.٥-٢٪.",
    usesEn: "In layer rations at 3-8%, and ruminants 0.5-2%.",
    pros: ["مصدر كالسيوم مركز ٣٨٪", "رخيص", "سهل المزج"],
    prosEn: ["Concentrated calcium 38%", "Cheap", "Easy to mix"],
    cons: ["زيادتها تتعارض مع امتصاص الفوسفور", "يجب توازن Ca:P"],
    consEn: ["Excess interferes with phosphorus absorption", "Ca:P balance needed"],
    whenToUse: "في علائق الدجاج البياض وقبل موسم الإنتاج.",
    whenToUseEn: "In layer rations and before production season.",
    whenNotToUse: "بكميات مفرطة تخل بتوازن الكالسيوم والفوسفور.",
    whenNotToUseEn: "In excessive amounts disrupting Ca:P balance.",
    alternatives: [],
  },
  bicarb: {
    key: "bicarb",
    category: "mineral",
    description: "بيكربونات الصوديوم تُستخدم كمخزن مؤقت للكرش لمنع الحماض خاصة في العلائق عالية التركيز.",
    descriptionEn: "Sodium bicarbonate is used as a rumen buffer to prevent acidosis, especially in high-concentrate rations.",
    uses: "في علائق الأبقار الحلوب عالية الإنتاج بنسبة ٠.٥-١.٢٪.",
    usesEn: "In high-producing dairy rations at 0.5-1.2%.",
    pros: ["يمنع حماض الكرش", "يحسن من إنتاج اللبن", "يستقر الـ pH"],
    prosEn: ["Prevents rumen acidosis", "Improves milk production", "Stabilizes pH"],
    cons: ["إضافته بكثرة يرفع الصوديوم", "يجب حساب الملح معه"],
    consEn: ["Excess raises sodium", "Must account for salt"],
    whenToUse: "في العلائق عالية الحبوب أو عند ظهور علامات حماض الكرش.",
    whenToUseEn: "In high-grain rations or when acidosis signs appear.",
    whenNotToUse: "في العلائق عالية الألياف المنخفضة التركيز.",
    whenNotToUseEn: "In high-fiber, low-concentrate rations.",
    alternatives: [],
  },
  salt: {
    key: "salt",
    category: "mineral",
    description: "ملح الطعام (كلوريد الصوديوم) ضروري لجميع الحيوانات، ينظم التوازن المائي ووظائف الأعصاب.",
    descriptionEn: "Salt (sodium chloride) is essential for all animals, regulating water balance and nerve functions.",
    uses: "في كل العلائق بنسبة ٠.٢-١٪ حسب نوع الحيوان.",
    usesEn: "In all rations at 0.2-1% depending on animal type.",
    pros: ["ضروري للحيوان", "رخيص", "يحفز الشرب"],
    prosEn: ["Essential for animals", "Cheap", "Stimulates drinking"],
    cons: ["الزيادة تسبب تسمم ملحي", "يجب حساب الصوديوم الكلي"],
    consEn: ["Excess causes salt toxicity", "Must calculate total sodium"],
    whenToUse: "في كل العلائق بكميات مدروسة.",
    whenToUseEn: "In all rations in calculated amounts.",
    whenNotToUse: "بكميات كبيرة للحيوانات التي لا تشرب ماء كافٍ.",
    whenNotToUseEn: "In large amounts for animals not drinking enough water.",
    alternatives: [],
  },
  mineral_mix: {
    key: "mineral_mix",
    category: "mineral",
    description: "مخلوط الأملاح المعدنية يحتوي على العناصر النادرة (زنك، نحاس، منجنيز، كوبالت، يود، سيلينيوم) الضرورية للصحة والإنتاج.",
    descriptionEn: "Mineral mix contains trace elements (zinc, copper, manganese, cobalt, iodine, selenium) essential for health and production.",
    uses: "في كل العلائق بنسبة ٠.٥-٢٪.",
    usesEn: "In all rations at 0.5-2%.",
    pros: ["يوفر العناصر النادرة", "يحسن المناعة", "يحسن الإنتاج"],
    prosEn: ["Provides trace elements", "Improves immunity", "Improves production"],
    cons: ["مكلف نسبياً", "الجودة تختلف بين المصادر"],
    consEn: ["Relatively expensive", "Quality varies between sources"],
    whenToUse: "في كل العلائق لضمان تغطية العناصر النادرة.",
    whenToUseEn: "In all rations to ensure trace element coverage.",
    whenNotToUse: "إذا كانت العليقة تحتوي على مخلوط معدني آخر (خطر التسمم).",
    whenNotToUseEn: "If the ration already contains another mineral mix (toxicity risk).",
    alternatives: [],
  },
  vitamins: {
    key: "vitamins",
    category: "vitamin",
    description: "مكمل الفيتامينات يوفر الفيتامينات الذائبة في الدهن (A, D, E) والمائية (B complex) الضرورية للنمو والمناعة.",
    descriptionEn: "Vitamin supplement provides fat-soluble (A, D, E) and water-soluble (B complex) vitamins essential for growth and immunity.",
    uses: "في كل العلائق بنسبة ٠.١-٠.٥٪.",
    usesEn: "In all rations at 0.1-0.5%.",
    pros: ["يحسن المناعة", "يدعم النمو", "يمنع نقص الفيتامينات"],
    prosEn: ["Improves immunity", "Supports growth", "Prevents vitamin deficiency"],
    cons: ["مكلف", "يتأثر بالحرارة والضوء", "مدة صلاحية محدودة"],
    consEn: ["Expensive", "Affected by heat and light", "Limited shelf life"],
    whenToUse: "في كل العلائق خاصة للحيوانات الصغيرة وعالية الإنتاج.",
    whenToUseEn: "In all rations, especially for young and high-producing animals.",
    whenNotToUse: "بكميات مفرطة (خطر فرط الفيتامينات الذائبة في الدهن).",
    whenNotToUseEn: "In excessive amounts (risk of fat-soluble vitamin toxicity).",
    alternatives: [],
  },
  toxin_binder: {
    key: "toxin_binder",
    category: "additive",
    description: "مضاد السموم يربط الفطريات والسموم في العليقة، يحمي الحيوان من الأفلاتوكسين والسموم الفطرية.",
    descriptionEn: "Toxin binder binds fungi and toxins in the ration, protecting animals from aflatoxin and mycotoxins.",
    uses: "في كل العلائق بنسبة ٠.١-٠.٥٪ خاصة في الصيف والرطوبة العالية.",
    usesEn: "In all rations at 0.1-0.5%, especially in summer and high humidity.",
    pros: ["يحمي من السموم الفطرية", "يحسن الأداء", "آمن للاستخدام"],
    prosEn: ["Protects from mycotoxins", "Improves performance", "Safe to use"],
    cons: ["مكلف", "قد يربط بعض العناصر الغذائية"],
    consEn: ["Expensive", "May bind some nutrients"],
    whenToUse: "في الصيف أو عند الشك في جودة العلف أو الرطوبة العالية.",
    whenToUseEn: "In summer or when feed quality is questionable or humidity is high.",
    whenNotToUse: "مع علف عالي الجودة مؤكد (يمكن الاستغناء عنه).",
    whenNotToUseEn: "With confirmed high-quality feed (can be omitted).",
    alternatives: [],
  },
};

/** Get ingredient detail by key, or null if not found. */
export function getIngredientDetail(key: string): IngredientDetail | null {
  return INGREDIENT_DETAILS[key] ?? null;
}

/** Get all ingredient detail keys. */
export const INGREDIENT_DETAIL_KEYS = Object.keys(INGREDIENT_DETAILS);
